package io.dolby.comms.sdk.flutter

object FlutterEvents {
    const val EVENT_NOTIFICATION_INVITATION_RECEIVED = "EVENT_NOTIFICATION_INVITATION_RECEIVED"
    const val EVENT_COMMAND_MESSAGE_RECEIVED = "EVENT_COMMAND_MESSAGE_RECEIVED"
    const val EVENT_CONFERENCE_PARTICIPANT_UPDATED = "EVENT_CONFERENCE_PARTICIPANT_UPDATED"
}